language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - cd ..
  - wget http://www.renpy.org/dl/6.99.1/renpy-6.99.1-sdk.tar.bz2
  - tar xf renpy-6.99.1-sdk.tar.bz2
  - rm renpy-6.99.1-sdk.tar.bz2
  - mv renpy-6.99.1-sdk renpy
  - cd renpy
# command to run tests
script:
  - coverage run ./renpy.sh "../ganbatte/" lint && ./renpy.sh launcher distribute "../ganbatte/"
after_success:
  coveralls
