language: python
python:
  - "2.7"
# set different builds using different version of Ren'Py
env:
  - renpy_version=6993
  - renpy_version=6991
  - renpy_version=6183
# command to install dependencies
install:
  - ./travis.sh
# command to run tests
script:
    - cd ..
    - cd renpy
    - ./renpy.sh "../ganbatte/" lint && ./renpy.sh launcher distribute "../ganbatte/" && ./renpy.sh launcher distribute "../ganbatte/" --package=android
